<?php
$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Title');
 
$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Description');
 
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
 
$form->setAttribute('action', $this->url('todo-app', ['action' => 'create']));
$form->prepare();
 
echo $this->form()->openTag($form);
?>
 
<div class="form-group">
   <?= $this->formLabel($title) ?>
   <?= $this->formElement($title) ?>
   <?= $this->formElementErrors()->render($title, ['class' => 'help-block text-danger']) ?>
</div>
 
<div class="form-group">
   <?= $this->formLabel($description) ?>
   <?= $this->formElement($description) ?>
   <?= $this->formElementErrors()->render($description, ['class' => 'help-block text-danger']) ?>
</div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>