<h4 class="d-flex justify-content-between align-items-center mb-3 mt-3">
   <span class="text-muted">Task List</span>
   <a class="btn btn-success ml-1" href="<?= $this->url('todo-app', ['action' => 'create'])?>">New Task</a>
</h4>
<table class="table table-hover">
   <thead>
   <tr>
		<th>ID</th>     
		<th>Title</th>
		<th>Created</th>
	   	<th>Ended</th>
	   	<th>Finished</th>
	   	<th>Actions</th>
   </tr>
   </thead>
   <tbody>
   <?php foreach ($this->tasks as $task) : ?>

	   <tr>
			<td><?= $this->escapeHtml($task->id) ?></td>	   
			<td><?= $this->escapeHtml($task->title) ?></td>
		   <td><?= $this->escapeHtml($task->creationDate) ?></td>
		   <td><?= $this->escapeHtml($task->finishDate) ?></td>
		   <td><?= $task->finished ? 'Yes' : 'No'?></td>
		   <td>
				<a class="btn btn-warning ml-1" href="<?= $this->url('todo-app', ['action' => 'edit', 'id' => $task->id])?>">Edit</a>
				<a class="btn btn-info ml-1" href="<?= $this->url('todo-app', ['action' => 'show','id' => $task->id])?>">View</a>
				<a class="btn btn-danger ml-1" onclick="return confirm('Are you sure you want to delete it?')" href="<?= $this->url('todo-app', ['action' => 'delete','id' => $task->id])?>">Delete</a>
		   </td>
	   </tr>
   <?php endforeach; ?>
   </tbody>
</table>