<?/*=var_dump($task)*/?>
<h1>Task Detail <?=$task->id ?></h1>

<div class="card w-75">
   <div class="card-header">
       <h4><?=$task->title ?></h4>
       <p>
           <small class="text-muted">Created at <?=$task->creationDate?></small>
       </p>
   </div>
   <div class="card-body">
       <p class="card-text">
           <?= $task->description ?>
       </p>
       <?php if ($task->finished != 1): ?>
           <a href="<?= $this->url('todo-app', [
               'action' => 'finished',
               'id' => $task->id
           ]) ?>" class="btn btn-primary">Mark as finished</a>
       <?php else: ?>
           <p>
               <span class="text text-danger">This task was finished!</span>
           </p>
       <?php endif; ?>
 
       <a href="<?= $this->url('todo-app') ?>" class="btn btn-secondary">Back</a>
   </div>
</div>